# Site settings
title:       Tim Varley
#email:       tim.varley@gmail.com
author:      Tim Varley
description: "Tim's Personal blog"
baseurl:     ""
url:         "http://tvarley.github.io"

# Google analytics
google_analytics: UA-4653080-9

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  true

# Social icons
show_social_icons: true
github_username: tvarley
gitlab_username: tvarley
twitter_username:
google_plus_id:
linkedin_username: timothyvarley
bitcoin_url:
paypal_url:
flattr_button:

plugins:
  - jemoji
  - jekyll-paginate

#redcarpet:
#  extensions: [fenced_code_blocks]

kramdown:
  input: GFM
  hard_wrap: false

# Build settings
# markdown: redcarpet
markdown: kramdown
permalink: short-urls-jekyll
# highlighter: rouge
paginate: 3
sass:
compressed: true
use_coderay: true
