# Site settings
title:       Tim Varley
email:       tim.varley@gmail.com
author:      Tim Varley
description: "Tim's Personal blog"
baseurl:     ""
url:         "http://tvarley.github.io"

# Google analytics
google_analytics: UA-4653080-9

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: true
github_username: tvarley
twitter_username: varleti
google_plus_id:
linkedin_username: timothyvarley
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true
